spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/eskimo
    username: root
    password: '01022074992'
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: create-drop

  jackson:
    deserialization:
      fail-on-unknown-properties : true

  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 215MB

  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

jwt:
  secretKey: govlepel@$&amp;


log:
  slack:
    enabled: true
    webHookUrl: https://hooks.slack.com/services/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
    channel: error-report-bot
  database:
    enabled: true
  level: ERROR


file:
  upload-dir: ./files
  projectimage-dir: ./files/projectimg
  profileimage-dir: ./files/profileimg


logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
