spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    properties:
      hibernate:
        show-sql: false
        format_sql: true
    hibernate:
      ddl-auto: create

  jackson:
    deserialization:
      fail-on-unknown-properties: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 215MB

  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  boot:
    admin:
      client:
        url: http://egluubootadmin.herokuapp.com/
        instance:
          service-url: https://egluuapi.codingnome.dev/

management:
  endpoints:
    web:
      exposure:
        include: '*'

jwt:
  secretKey: EGLUUSecretKeyV1ThisDataMustBeHide


log:
  slack:
    enabled: true
    webHookUrl: ${SLACK_URL}
    channel: error-report-bot
  database:
    enabled: true
  level: ERROR


file:
  upload-dir: ./files
  project:
    dir: ./files/projectimg
    defaultImg: ./files/projectimg/defaultImage.png
  profile:
    dir: ./files/profileimg
    defaultImg: ./files/profileimg/defaultImage.png


logging:
  level:
    root: info
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
