= Eskiiimo REST API Guide
Eskiiimo;
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 4
:sectlinks:
:operation-http-request-title: Example request
:operation-response-body-title: Example response
:docinfo: shared

[[overview]]
= 개요

[[overview-http-verbs]]
== HTTP 동사

본 REST API에서 사용하는 HTTP 동사(verbs)는 가능한한 표준 HTTP와 REST 규약을 따릅니다.

|===
| 동사 | 용례

| `GET`
| 리소스를 가져올 때 사용

| `POST`
| 새 리소스를 만들 때 사용

| `PUT`
| 기존 리소스를 수정할 때 사용

| `PATCH`
| 기존 리소스의 일부를 수정할 때 사용

| `DELETE`
| 기존 리소스를 삭제할 떄 사용
|===

[[overview-http-status-codes]]
== HTTP 상태 코드

본 REST API에서 사용하는 HTTP 상태 코드는 가능한한 표준 HTTP와 REST 규약을 따릅니다.

|===
| 상태 코드 | 용례

| `200 OK`
| 요청을 성공적으로 처리함

| `201 Created`
| 새 리소스를 성공적으로 생성함. 응답의 `Location` 헤더에 해당 리소스의 URI가 담겨있다.

| `204 No Content`
| 기존 리소스를 성공적으로 수정함.

| `400 Bad Request`
| 잘못된 요청을 보낸 경우. 응답 본문에 더 오류에 대한 정보가 담겨있다.

| `404 Not Found`
| 요청한 리소스가 없음.
|===

[[overview-errors]]
== 오류

에러 응답이 발생했을 때 (상태 코드 >= 400), 본문에 해당 문제를 기술한 JSON 객체가 담겨있다.
[[AuthApiError]]
=== Auth Api Error
[[E001]]
==== Error001
operation::001[snippets='response-body']
[[E002]]
==== Error002
operation::002[snippets='response-body']
[[E003]]
==== Error003
operation::003[snippets='response-body']
[[E004]]
==== Error004
operation::004[snippets='response-body']
[[E005]]
==== Error005
operation::005[snippets='response-body']
[[E006]]
==== Error006
operation::006[snippets='response-body']
[[E007]]
==== Error007
operation::007[snippets='response-body']
[[ProjectApiError]]
=== Project Api Error
[[E101]]
==== Error101
operation::101[snippets='response-body']
[[E102]]
==== Error102
operation::102[snippets='response-body']
[[E103]]
==== Error103
operation::103[snippets='response-body']
[[E104]]
==== Error104
operation::104[snippets='response-body']
[[E105]]
==== Error105
operation::105[snippets='response-body']
[[E106]]
==== Error106
operation::106[snippets='response-body']
[[E107]]
==== Error107
operation::107[snippets='response-body']
[[E108]]
==== Error108
operation::108[snippets='response-body']
[[E109]]
==== Error109
operation::109[snippets='response-body']
[[UserApiError]]
=== User Api Error
[[E201]]
==== Error201
operation::201[snippets='response-body']
[[E202]]
==== Error202
operation::202[snippets='response-body']
[[E203]]
==== Error203
operation::203[snippets='response-body']

[[overview-hypermedia]]
== 하이퍼미디어

본 REST API는 하이퍼미디어와 사용하며 응답에 담겨있는 리소스는 다른 리소스에 대한 링크를 가지고 있다.
응답은 http://stateless.co/hal_specification.html[Hypertext Application from resource to resource. Language (HAL)] 형식을 따른다.
링크는 `_links`라는 키로 제공한다. 본 API의 사용자(클라이언트)는 URI를 직접 생성하지 않아야 하며, 리소스에서 제공하는 링크를 사용해야 한다.

[[index]]
=== 인덱스 API

[[indexProjectsDetail]]
==== 프로젝트 상세 페이지 인덱스

operation::index-projects-detail[snippets='http-request,response-body,links']

[[indexProfile]]
==== 프로필 페이지 인덱스

operation::index-profile[snippets='http-request,response-body,links']

[[auth]]
=== 인증 API

[[signIn]]
==== 로그인

operation::signin[snippets='http-request,response-body']

[[SignUp]]
==== 회원 가입

operation::signup[snippets='http-request,response-body']

[[IdCheck]]
==== 아이디 중복 체크

operation::idCheck[snippets='http-request,response-body']

[[projectList]]
=== 프로젝트 리스트 API

[[resourcesProjectList]]
==== 프로젝트 목록 조회

operation::get-projects[snippets='http-request,request-parameters,response-body']


[[resourcesDeadlineProjectList]]
==== 마감 임박 프로젝트 목록 조회

operation::get-deadline-projects[snippets='http-request,request-parameters,response-body']

[[projectDetail]]
=== 프로젝트 상세 API

[[resourcesProjectGet]]
==== 프로젝트 상세 데이터 조회

operation::query-project[snippets='http-request,path-parameters,response-body']
===== 일반 사용자
operation::query-project[snippets='links']
===== 팀장
operation::query-my-project[snippets='links']


[[resourcesProjectCreate]]
==== 프로젝트 생성

operation::create-project[snippets='http-request,response-body']


[[resourcesProjectUpdate]]
==== 프로젝트 수정

operation::update-project[snippets='http-request,path-parameters,response-body']

[[resourcesProjectDelete]]
==== 프로젝트 삭제

operation::delete-project[snippets='http-request,path-parameters,response-body']

[[Apply]]
=== 프로젝트 지원 API

[[projectApply]]
==== 프로젝트 지원하기

operation::applyProject[snippets='http-request,path-parameters,response-body']

[[updateApply]]
==== 프로젝트 지원서 수정

operation::updateApply[snippets='http-request,path-parameters,response-body']

[[getApplicants]]
==== 프로젝트 지원자 리스트 조회

operation::getApplicants[snippets='http-request,path-parameters,response-body']

[[getApply]]
==== 프로젝트 지원서 조회

operation::getApply[snippets='http-request,path-parameters,response-body']
===== 팀장
operation::getApply[snippets='links']
===== 본인의 지원서 일 때
operation::getMyApply[snippets='links']

[[acceptApply]]
==== 프로젝트 지원자 승인

operation::acceptApply[snippets='http-request,path-parameters,response-body']

[[rejectApply]]
==== 프로젝트 지원자 거절

operation::rejectApply[snippets='http-request,path-parameters,response-body']

[[Recruit]]
=== 프로젝트 영입 API

[[projectRecruit]]
==== 프로젝트 영입

operation::projectRecruit[snippets='http-request,path-parameters,response-body']

[[getRecruits]]
==== 나에게 온 영입제안 리스트 조회

operation::getRecruits[snippets='http-request,path-parameters,response-body']

[[getSendRecruits]]
==== 내가 보낸 영입 리스트 조회

operation::getSendRecruits[snippets='http-request,path-parameters,response-body']


[[getRecruit]]
==== 나에게 온 영입제안 조회

operation::getRecruit[snippets='http-request,path-parameters,response-body,links']

[[acceptRecruit]]
==== 프로젝트 영입 승인

operation::acceptRecruit[snippets='http-request,path-parameters,response-body']

[[rejectRecruit]]
==== 프로젝트 영입 거절

operation::rejectRecruit[snippets='http-request,path-parameters,response-body']

[[People]]
=== 팀을 찾는 사람들 API

[[resourcesPeople]]
==== 팀을 찾는 사람들 목록 조회

operation::get-people[snippets='http-request,request-parameters,response-body']

[[profile]]
=== 프로필 API

[[resourcesProfileGet]]
==== 프로필 조회

operation::query-profile[snippets='http-request,path-parameters,response-body']
===== 일반 사용자
operation::query-profile[snippets='links']
===== 내 프로필
operation::query-my-profile[snippets='links']

[[resourcesRunningProjectList]]
==== 사용자가 참여중인 프로젝트

operation::get-running-project[snippets='http-request,request-parameters,response-body']


[[resourcesPlannedProjectList]]
==== 사용자가 기획한 프로젝트

operation::get-planned-project[snippets='http-request,request-parameters,response-body']


[[resourcesEndedProjectList]]
==== 사용자가 참여했던 프로젝트
operation::get-ended-project[snippets='http-request,request-parameters,response-body']

[[resourcesRunningHiddenProjectList]]
==== 사용자가 참여중인 숨겨진 프로젝트

operation::get-running-hidden-project[snippets='http-request,request-parameters,response-body']


[[resourcesPlannedHiddenProjectList]]
==== 사용자가 기획한 숨겨진 프로젝트

operation::get-planned-hidden-project[snippets='http-request,request-parameters,response-body']


[[resourcesEndeHiddendProjectList]]
==== 사용자가 참여했던 숨겨진 프로젝트

operation::get-ended-hidden-project[snippets='http-request,request-parameters,response-body']

[[hideProject]]
==== 프로젝트 숨기기

operation::hideProject[snippets='http-request,path-parameters,response-body']

[[reshowProject]]
==== 프로젝트 다시 보이게 하기

operation::reshowProject[snippets='http-request,path-parameters,response-body']

[[resourcesProfileUpdate]]
==== 프로필 업데이트

operation::update-profile[snippets='http-request,response-body']

[[File]]
=== File Api

[[resourcesProfileImageUpload]]
==== 프로필 이미지 업로드

operation::upload-profile-image[snippets='path-parameters,curl-request,response-body']

[[resourcesProjectImageUpload]]
====  프로젝트 이미지 업로드

operation::upload-project-image[snippets='path-parameters,curl-request,response-body']

